# Generated by Django 4.1.7 on 2023-03-04 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentName', models.CharField(max_length=255)),
                ('studentMajor', models.CharField(max_length=255)),
                ('studentAge', models.IntegerField()),
            ],
        ),
    ]
